#!/usr/bin/env python3
"""Generates docs/submission/FINAL_REQUIREMENT_MATRIX.md (judge view) from docs/compliance/FINAL_REQUIREMENT_MATRIX.md (the machine-checked source)."""
import re
src = open("docs/compliance/FINAL_REQUIREMENT_MATRIX.md").read().split("\n")
rows = [[x.strip() for x in l[2:-2].split(" | ")] for l in src if re.match(r"\| [A-Z]{2}-\d\d \|", l)]
cnt = {}
for r in rows: cnt[r[9]] = cnt.get(r[9], 0) + 1
moment = {"MB-01": "Video 0:00 dashboard; Fig. 5", "MB-04": "Video 1:25-2:45; Figs 5-8", "NF-04": "Video 4:20 matrix (FAIL shown)", "LV-02": "Video 2:05 map; Fig. 5", "TE-07": "Video 3:20 Copilot; Fig. 13", "TS-06": "Video 3:55 engineering montage"}
out = ["# Final requirement matrix (judge view)", "",
 "Generated by `tools/dev/build_submission_matrix.py` from the machine-checked source `docs/compliance/FINAL_REQUIREMENT_MATRIX.md` (gate: `go run ./tools/reqtrace`). Counts are computed, not typed.", "",
 f"**{len(rows)} requirements: PASS {cnt.get('PASS',0)} · PARTIAL {cnt.get('PARTIAL',0)} · BLOCKED {cnt.get('BLOCKED',0)} · FAIL {cnt.get('FAIL',0)} · NOT VERIFIED 0** (anything not verified is carried as PARTIAL/BLOCKED with its gap).", "",
 "| ID | Official requirement | Source | VoltSight implementation | Verification | Evidence | Status | Judge explanation (measured) | Limitation | Video / figure moment |", "|---|---|---|---|---|---|---|---|---|---|"]
for r in rows:
    out.append("| " + " | ".join([r[0], r[1], r[2], r[3], r[4], r[5], "**" + r[9] + "**", r[6], r[8], moment.get(r[0], "—")]) + " |")
open("docs/submission/FINAL_REQUIREMENT_MATRIX.md", "w").write("\n".join(out) + "\n")
print(cnt)
